# Generated by Django 2.0.5 on 2018-06-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180611_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Answer',
        ),
    ]
